# Generated by Django 4.2.30 on 2026-04-30 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NetworkDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("router", "Router"),
                            ("switch", "Switch"),
                            ("olt", "OLT"),
                            ("onu", "ONU"),
                            ("ap", "Access Point"),
                            ("other", "Other"),
                        ],
                        default="router",
                        max_length=20,
                    ),
                ),
                ("brand", models.CharField(blank=True, max_length=100)),
                ("model_no", models.CharField(blank=True, max_length=100)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("mac_address", models.CharField(blank=True, max_length=17)),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("maintenance", "Maintenance"),
                        ],
                        default="online",
                        max_length=20,
                    ),
                ),
                ("install_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="customers.area",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="IPPool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "subnet",
                    models.CharField(help_text="e.g. 192.168.1.0/24", max_length=50),
                ),
                ("gateway", models.GenericIPAddressField()),
                ("dns_primary", models.GenericIPAddressField(default="8.8.8.8")),
                (
                    "dns_secondary",
                    models.GenericIPAddressField(
                        blank=True, default="8.8.4.4", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="customers.area",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
