# Generated by Django 4.2.30 on 2026-04-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="networkdevice",
            name="api_host",
            field=models.CharField(
                blank=True,
                help_text="IP address MikroTik API listens on (usually same as device IP)",
                max_length=100,
                verbose_name="API Host/IP",
            ),
        ),
        migrations.AddField(
            model_name="networkdevice",
            name="api_password",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="API Password"
            ),
        ),
        migrations.AddField(
            model_name="networkdevice",
            name="api_port",
            field=models.PositiveIntegerField(
                default=8728,
                help_text="Default: 8728 (unencrypted) or 8729 (SSL)",
                verbose_name="API Port",
            ),
        ),
        migrations.AddField(
            model_name="networkdevice",
            name="api_use_ssl",
            field=models.BooleanField(default=False, verbose_name="Use SSL"),
        ),
        migrations.AddField(
            model_name="networkdevice",
            name="api_username",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="API Username"
            ),
        ),
        migrations.AddField(
            model_name="networkdevice",
            name="is_mikrotik",
            field=models.BooleanField(default=False, verbose_name="MikroTik Router"),
        ),
    ]
