# Generated by Django 4.2.30 on 2026-05-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_networkdevice_api_host_networkdevice_api_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="networkdevice",
            name="radius_secret",
            field=models.CharField(
                blank=True,
                help_text="Shared secret between this router and FreeRADIUS (NAS secret)",
                max_length=100,
                verbose_name="RADIUS Secret",
            ),
        ),
    ]
