# Generated by Django 4.2.30 on 2026-04-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "package_type",
                    models.CharField(
                        choices=[
                            ("fiber", "Fiber"),
                            ("cable", "Cable"),
                            ("wireless", "Wireless"),
                        ],
                        default="fiber",
                        max_length=20,
                    ),
                ),
                (
                    "speed_download",
                    models.PositiveIntegerField(help_text="Download speed in Mbps"),
                ),
                (
                    "speed_upload",
                    models.PositiveIntegerField(help_text="Upload speed in Mbps"),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "duration_days",
                    models.PositiveIntegerField(
                        default=30, help_text="Billing cycle in days"
                    ),
                ),
                (
                    "data_limit_gb",
                    models.PositiveIntegerField(
                        blank=True, help_text="0 or blank = unlimited", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["price"],
            },
        ),
    ]
