# Generated by Django 4.2.30 on 2026-04-30 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_networkdevice_api_host_networkdevice_api_password_and_more"),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="connection",
            name="mikrotik_router",
            field=models.ForeignKey(
                blank=True,
                help_text="Router that manages this PPPoE user",
                limit_choices_to={"is_mikrotik": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="connections",
                to="network.networkdevice",
                verbose_name="MikroTik Router",
            ),
        ),
    ]
