# Generated by Django 4.2.30 on 2026-05-01 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resellers", "0001_initial"),
        ("customers", "0002_connection_mikrotik_router"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="reseller",
            field=models.ForeignKey(
                blank=True,
                help_text="Franchise / Dealer / Sub-Dealer who owns this customer",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customers",
                to="resellers.reseller",
            ),
        ),
    ]
